version: '3'

networks:
  default:
    external:
      name: latelier

services:
  superset:
    build:
      context: .
      args:
        proxy: ${http_proxy}
        SUPERSET_VERSION: 0.22.1
    container_name: superset
    image: superset
    volumes:
      - ./config:/etc/superset
      - ./data:/var/lib/superset
    ports:
      - 8080:8088
